services:
  app:
    image: cosmtrek/air
    container_name: go-animals
    env_file: ./.env
    working_dir: /app
    volumes:
      - ./:/app
    networks:
      - backend
      - backend_test
    hostname: animals-rest
    ports:
      - "8080:3000"
  postgres:
    image: postgres:alpine
    container_name: postgres_db
    env_file: ./.env
    volumes:
      - ./docker-postgresql-multiple-databases:/docker-entrypoint-initdb.d
    networks:
     - backend
    ports:
      - "3001:5432"

networks:
  backend:
    driver: bridge
  backend_test:
    driver: bridge
