name: prod_app

x-env-files: &env-files
  env_file:
    - ./env/.env
    - ./env/.prod.env

services:
  app:
    build:
      context: ./app
    volumes:
      - app:/home/app
    <<: *env-files
  postgres:
    <<: *env-files

volumes:
  app: